#!/usr/bin/env zsh

setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt prompt_subst
setopt AUTO_CD
setopt HIST_NO_FUNCTIONS # do not save function commands

# auto completion and suggestions
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
zstyle ':completion:*' matcher-list 'r:|=*' 'l:|=*' 'r:|=* m:{a-z\-}={A-Z\_}'
zstyle ':completion:*' list-dirs-first true

fpath=(~/.local/share/zsh/site-functions $fpath)

autoload -U +X bashcompinit && bashcompinit
autoload -Uz compinit
compinit -u

export HISTORY_TIME_FORMAT="%Y-%m-%d %T "
export HISTFILE=$HOME/.zsh_history
export HISTSIZE=9999
export SAVEHIST=9999
export EDITOR=nvim
export VISUAL=nvim
export TASK_EXE='go-task'
export CODEBOX_DIR=~/codebox
export LG_CONFIG_FILE=~/.config/lazygit/config.yml
export STARSHIP_CONFIG=~/.config/starship/config.toml
export TF_PLUGIN_CACHE_DIR="$HOME/.cache/terraform-plugins"
export SAM_CLI_TELEMETRY=0
export TANSTACK_CLI_TELEMETRY_DISABLED=1
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin:$GOPATH/bin/bin:$HOME/.cargo/bin:$HOME/.bun/bin:$HOME/.local/bin
export LIBVIRT_DEFAULT_URI="qemu:///system"
export FZF_DEFAULT_OPTS=" \
--preview-window='border-rounded' --prompt='❯ ' \
--marker='● ' --pointer='▶ ' --separator='─' --scrollbar='▌' --highlight-line \
--layout=reverse"

alias .....='cd ../../../..'
alias ....='cd ../../..'
alias ...='cd ../..'
alias ..='cd ..'
alias b=bat
alias ccclone='tbx-v1 codecommit clone --input-file ~/.config/tbx/cc-clone.yml -o ~/.config/tbx/.out/cc-clone.yml'
alias c=clear
alias ch="cliphist list | fzf --no-sort -d $'\t' --with-nth 2 | cliphist decode | wl-copy"
alias cp-awsprofile=" sel-awsprofile | tr -d '\n' | wl-copy"
alias cr='cargo run -- '
alias crq='cargo run -q -- '
alias gd='git diff'
alias ghclone='ghs eu; tbx-v1 github clone --input-file ~/.config/tbx/gh-clone.yml -o ~/.config/tbx/.out/gh-clone.yml'
alias gl="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) %C(dim white)%<(16)%an%C(reset) %C(bold green)%<(14)%ar%C(reset) %C(white)%s%C(reset)%C(auto)%d%C(reset)' --all"
alias gp='git pull --all --prune'
alias histcopy=' fc -ln 1 |fzf --tac --scheme=history |xargs -r -I {} wl-copy "{}"'
alias hist='history -E'
alias kdd='kubectl describe deploy'
alias kd='kubectl describe'
alias kdp='kubectl describe pod'
alias kds='kubectl describe service'
alias ke='kubectl exec'
alias kgd='kubectl get deploy'
alias kg='kubectl get'
alias kgp='kubectl get pods'
alias kgs='kubectl get service'
alias k=kubectl
alias kl='kubectl logs'
alias lazydocker=' CONFIG_DIR=~/.config/lazydocker lazydocker'
alias lazygit=' lazygit'
alias lg=lazygit
alias lla='ll -A'
alias ll=' eza -l --group-directories-first --git --git-repos --icons --ignore-glob ".DS_Store"'
alias ls='ls --color=auto'
alias lt=' eza -l --group-directories-first --ignore-glob ".git|.DS_Store" -aTL'
alias lzd=lazydocker
alias mos-gh-clone='ghs i; mos-gh-clone'
alias m='mise'
alias mt='mise tasks'
alias mr='mise run'
alias ml='mise ls --local'
alias oc='opencode'
alias randbase64="openssl rand 60 | base64 -w 0 | tr -d '\n' | wl-copy"
alias randraw="openssl rand -hex 32 | tr -d '\n' | wl-copy"
alias sel-awsprofile="grep -E '^\[.+\]$' ~/.aws/credentials | sed -E 's/^\[(.+)\]$/\1/' | sort -u | fzf"
alias task='go-task'
alias tf=terraform
alias ts='tailscale'
alias t='tmux a || tmux'
alias v='nvim'
# zshaddhistory() { [[ $1 != (gb |gc |gg )* ]] }

ytv() { yt-dlp --cookies-from-browser firefox --no-playlist --progress -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]" --merge-output-format mp4 -o "$HOME/Downloads/%(title)s.%(ext)s" "$1"; }
yta() { yt-dlp --cookies-from-browser firefox --no-playlist --progress -x --audio-format mp3 --audio-quality 0 -o "$HOME/Downloads/%(title)s.%(ext)s" "$1"; }

gb() {
  branch=$(git branch -a | grep -v 'HEAD ->' | sed 's/^[* ]*//' | sed 's|remotes/||' | sort -u | \
    fzf --preview "git log --oneline --color=always {}" --prompt "Git branch: ")
  [[ -n "$branch" ]] && { git switch "${branch#origin/}"; gp || true; }
}

gc() {
  files=$(git -c color.status=always status --short | \
    fzf --multi --ansi --bind 'ctrl-a:select-all' \
        --preview 'git diff -- {2} | delta --width=$FZF_PREVIEW_COLUMNS' \
        --preview-window=right:81% | awk '{print $2}')
  [[ -z "$files" ]] && return
  msg=$(gum input --placeholder "Commit message...")
  [[ -z "$msg" ]] && return
  echo "$files" | xargs git add && git commit -m "$msg"
}

goto_repodir() {
  local base_dir="$1"
  local query="$2"
  local max_depth="4"
  dir=$(fd -t d -H --max-depth $max_depth -g '.git' \
      --base-directory $base_dir --prune |
      sed 's:/\.git/*$::' |
      fzf --height=36% --query "$query" --prompt="Git Repo: ")
  [[ -n "$dir" ]] && cd "$base_dir/$dir"
}

gg() { goto_repodir $CODEBOX_DIR "$1" }

ghs() {
  gh auth status --json 'hosts' --jq '.hosts."github.com".[].login' |
    fzf --height=4 --query "$1" --prompt "Github user: " |
    xargs -r -I {} gh auth switch -u {}
}

pinstall() {
  paru -Slq | fzf \
    --preview "paru -Si {}" \
    --preview-window=right:67%:wrap \
    --height=36% \
    --prompt="Install: " |
    xargs -r paru -S --needed --noconfirm
}

premove() {
  paru -Qq | fzf \
    --preview "paru -Qi {}" \
    --preview-window=right:78%:wrap \
    --height=33% \
    --prompt="Remove: " |
    xargs -r paru -Rns
}

pinfo() {
  paru -Qq | fzf \
    --preview "paru -Qi {}" \
    --preview-window=right:78%:wrap \
    --height=33% \
    --prompt="Info: " | xargs -r wl-copy
}

kwhere() {
  printf 'Ctx: %s\nNS : %s\n' \
       "$(kubectl config current-context)" \
       "$(kubectl config view --minify -o jsonpath='{..namespace}')" | sed 's/NS : $/NS : default/'
}

kn() {
  local ns
  ns=$(kubectl get ns -o jsonpath='{.items[*].metadata.name}' |tr ' ' '\n' |fzf \
      --preview "kubectl describe ns {}" \
      --preview-window=right:78%:wrap \
      --height=18 \
      --prompt="Switch Namespace: ")
  [[ -n "$ns" ]] && kubectl config set-context --current --namespace $ns
}

kc() {
  local ctx
  ctx=$(kubectl config get-contexts -o name |fzf \
      --height=9 \
      --prompt="Switch Context: ")
  [[ -n "$ctx" ]] && kubectl config use-context $ctx
}

eval "$(mise activate zsh)"
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
eval "$(task --completion zsh)"
source <(fzf --zsh)
source <(gh completion -s zsh)
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# source /usr/share/nvm/init-nvm.sh

complete -C "$(which aws_completer)" aws
# complete -o nospace -C "$(which terraform)" terraform

if command -v tbx-v1 &>/dev/null; then
  source <(tbx-v1 completion zsh)
fi

# if command -v op &>/dev/null; then
#   eval "$(op completion zsh)"
#   compdef _op op
# fi

# if command -v mise &>/dev/null; then
#   source <(mise completion zsh)
# fi

# source <(gum completion zsh)

if command -v tea &>/dev/null; then
  source <(tea completion zsh)
fi

[[ -f ~/.customrc.sh ]] && source ~/.customrc.sh
